# ===================================================================
# Standard Spring Boot properties
# ===================================================================
project:
  version: @project.version@

server:
  port: 8080
  tomcat:
    accesslog:
      directory: /var/log/idporten-bekreft-kontaktinfo/
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
    remote-ip-header: X-Forwarded-For
    basedir: "/opt/idporten-bekreft-kontaktinfo/tmp"
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

# Spring boot actuator endpoint
management:
  metrics:
    tags:
      application: "Idporten-bekreft-kontaktinfo"
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health, info, version, prometheus"
  endpoint:
    health:
      show-details: always
      enabled: true
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false
    diskspace:
      enabled: false
    metrics:
      enabled: false


spring:
  mvc:
    throw-exception-if-no-handler-found: true

  http:
    encoding:
      force: true

  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true

# ===================================================================
# Application specific properties
# ===================================================================
krr:
  url: 'http://eid-systest-admin01.dmz.local:10002/kontaktinfo-backend'
  timeout:
    read: 10000
    connect: 10000
  tip_days_user: 5

par:
  cache:
    ttl-in-s: 120

cache:
  local:
    ttl-in-s: 120
  cluster:
    ttl-in-s: 300
    transport:
      file:
        location: c:/etc/opt/idporten-oidc-provider/
