# https://github.com/codeceptjs/CodeceptJS/tree/3.x/docker
version: '3.5'
services:
  codeceptjs:
    image: ${REGISTRY}/codeceptjs-with-tests:${VERSION}
    environment:
      - CODECEPT_ARGS=--reporter mocha-multi --steps --verbose
    entrypoint: bash -c "/codecept/docker/run.sh; /codecept/bin/http-server /tests"
    ports:
      - 8080
    networks:
      atest:
    deploy:
      restart_policy:
        condition: none

networks:
  atest:
    driver: overlay
    attachable: true